const $ = (q) => document.querySelector(q);
const initialState = {spans:[{length:14,E:200,I:100000000}],supports:[{id:1,type:'pin',position:0,settlement:0},{id:2,type:'fixed',position:14,settlement:0},{id:3,type:'internal_hinge',position:8,settlement:0}],loads:[{id:1,type:'point',value:8,position:3,angle:0},{id:2,type:'point',value:10,position:6,angle:0},{id:3,type:'udl',value:4,value2:4,position:8,to:14}]};
const clone = (x) => JSON.parse(JSON.stringify(x));
let state = clone(initialState), history = [], future = [], pyodide = null, solverReady = false, zoom = 1, showValues = true, showFeatures = true;
const totalLength = () => state.spans.reduce((s,x)=>s+Number(x.length||0),0);
const esc = v => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const kind = v => String(v||'').toLowerCase().replaceAll(' ','_').replaceAll('-','_');
function snapshot(){history.push(clone(state));if(history.length>50)history.shift();future=[];}
function restore(next){state=clone(next);render();}
function supportSymbol(type,x,y){
  if(type==='internal_hinge') return `<g class="hinge-symbol" aria-label="Internal hinge"><circle cx="${x}" cy="${y}" r="11" class="hinge-ring"/><circle cx="${x}" cy="${y}" r="4" class="hinge-core"/></g>`;
  if(type==='fixed') return `<g class="fixed-symbol"><line x1="${x}" y1="${y-28}" x2="${x}" y2="${y+28}"/><path d="M ${x-20} ${y-22} l20 -8 M ${x-20} ${y-8} l20 -8 M ${x-20} ${y+6} l20 -8 M ${x-20} ${y+20} l20 -8"/></g>`;
  const tri=`<path d="M ${x-18} ${y+20} L ${x} ${y-10} L ${x+18} ${y+20} Z" class="support-triangle"/>`;
  return type==='roller'?`${tri}<circle cx="${x-8}" cy="${y+25}" r="5" class="roller"/><circle cx="${x+8}" cy="${y+25}" r="5" class="roller"/>`:tri;
}
function renderInputs(){
  $('#spanRows').innerHTML=state.spans.map((s,i)=>`<tr><td>${i+1}</td><td><input type="number" step="any" data-span="${i}" data-field="length" value="${s.length}"></td><td><input type="number" step="any" data-span="${i}" data-field="E" value="${s.E}"></td><td><input type="number" step="any" data-span="${i}" data-field="I" value="${s.I}"></td><td><button class="danger" data-remove-span="${i}">×</button></td></tr>`).join('');
  $('#supportRows').innerHTML=state.supports.map((s,i)=>`<tr><td>${i+1}</td><td><select data-support="${i}" data-field="type"><option value="pin" ${s.type==='pin'?'selected':''}>Pin</option><option value="roller" ${s.type==='roller'?'selected':''}>Roller</option><option value="fixed" ${s.type==='fixed'?'selected':''}>Fixed</option><option value="internal_hinge" ${s.type==='internal_hinge'?'selected':''}>Internal Hinge</option></select></td><td><input type="number" step="any" data-support="${i}" data-field="position" value="${s.position}"></td><td><input type="number" step="any" data-support="${i}" data-field="settlement" value="${s.settlement||0}"></td><td><button class="danger" data-remove-support="${i}">×</button></td></tr>`).join('');
  $('#loadRows').innerHTML=state.loads.map((l,i)=>{
    const t=kind(l.type), isU=t==='udl', isP=t==='point'||t==='point_load';
    return `<tr><td>${i+1}</td><td>${isU?'UDL / varying':t==='moment'?'Moment':'Point'}</td><td><input type="number" step="any" data-load="${i}" data-field="value" value="${l.value}"></td><td>${isU?`<input type="number" step="any" data-load="${i}" data-field="value2" value="${l.value2 ?? l.value}">`:'—'}</td><td>${isP?`<input type="number" step="any" data-load="${i}" data-field="angle" value="${l.angle||0}">`:'—'}</td><td><input type="number" step="any" data-load="${i}" data-field="position" value="${l.position}"></td><td>${isU?`<input type="number" step="any" data-load="${i}" data-field="to" value="${l.to}">`:'—'}</td><td><button class="danger" data-remove-load="${i}">×</button></td></tr>`;
  }).join('');
}
function renderBeam(){
  const width=1100,height=260,pad=70,beamY=105,L=Math.max(totalLength(),1),sx=(width-2*pad)/L,X=p=>pad+Number(p)*sx;
  const supports=state.supports.map((s,i)=>{const x=X(s.position);const label=s.type==='internal_hinge'?`H${i+1} · Internal Hinge`:`S${i+1} · ${s.type[0].toUpperCase()+s.type.slice(1)}`;return `<g>${supportSymbol(s.type,x,beamY)}<circle cx="${x}" cy="${beamY}" r="9" class="node"/><text x="${x}" y="${beamY+50}" class="support-label" text-anchor="middle">${esc(label)}</text><text x="${x}" y="${beamY+67}" class="position-label" text-anchor="middle">@ ${Number(s.position).toFixed(2).replace(/\.00$/,'')} m</text></g>`}).join('');
  const loads=state.loads.map(l=>{const x=X(l.position),t=kind(l.type);
    if(t==='moment') return `<g class="moment-load"><path d="M ${x+14} ${beamY-10} A 18 18 0 1 0 ${x-5} ${beamY-17}"/><text x="${x}" y="30" text-anchor="middle">${l.value} kN·m</text></g>`;
    if(t==='udl'){const x2=X(l.to),label=(Number(l.value2??l.value)===Number(l.value)?`−${l.value}`:`−${l.value} → −${l.value2}`)+' kN/m';let arrows='';for(let a=x;a<=x2+1;a+=Math.max(25,(x2-x)/12))arrows+=`<line x1="${a}" y1="55" x2="${a}" y2="${beamY-5}"/><path d="M ${a-4} ${beamY-11} L ${a} ${beamY-3} L ${a+4} ${beamY-11}"/>`;return `<g class="udl-load"><line x1="${x}" y1="55" x2="${x2}" y2="55"/><text x="${(x+x2)/2}" y="40" text-anchor="middle">${label}</text>${arrows}</g>`;}
    const angle=Number(l.angle||0);return `<g class="point-load"><line x1="${x}" y1="25" x2="${x}" y2="${beamY-4}"/><path d="M ${x-6} ${beamY-14} L ${x} ${beamY-3} L ${x+6} ${beamY-14}"/><text x="${x}" y="20" text-anchor="middle">−${l.value} kN${angle?` @ ${angle}°`:''}</text></g>`;
  }).join('');
  const inner=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Beam model">${loads}<line x1="${pad}" y1="${beamY}" x2="${width-pad}" y2="${beamY}" class="beam-line"/>${supports}<line x1="${pad}" y1="${beamY+100}" x2="${width-pad}" y2="${beamY+100}" class="dimension-line"/><text x="${width/2}" y="${beamY+125}" class="dimension-text" text-anchor="middle">${L.toFixed(2).replace(/\.00$/,'')} m</text></svg>`;
  $('#beamCanvas').innerHTML=inner;$('#beamCanvas').style.transform=`scale(${zoom})`;$('#beamCanvas').style.transformOrigin='top left';$('#zoomValue').textContent=`${Math.round(zoom*100)}%`;
}
function render(){renderInputs();renderBeam();}
function chart(el,samples,key,label,unit,features=[]){
  if(!samples.length){el.innerHTML='<div class="empty">No data.</div>';return;}
  const W=760,H=280,p=45,xs=samples.map(s=>s.x),ys=samples.map(s=>s[key]);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(0,...ys),ymax=Math.max(0,...ys);if(Math.abs(ymax-ymin)<1e-12){ymax+=1;ymin-=1;}const X=x=>p+(x-xmin)/(xmax-xmin||1)*(W-2*p),Y=y=>H-p-(y-ymin)/(ymax-ymin)*(H-2*p),path=samples.map((s,i)=>`${i?'L':'M'} ${X(s.x).toFixed(2)} ${Y(s[key]).toFixed(2)}`).join(' '),zero=Y(0);let marks='';if(showFeatures)marks=features.map(f=>`<line x1="${X(f.x)}" y1="${p}" x2="${X(f.x)}" y2="${H-p}" class="chart-feature"/>`).join('');let labels='';if(showValues){const step=Math.max(1,Math.floor(samples.length/8));labels=samples.filter((_,i)=>i%step===0).map(s=>`<text x="${X(s.x)}" y="${Y(s[key])-6}" class="chart-value" text-anchor="middle">${Number(s[key]).toFixed(key.includes('rotation')?4:3)}</text>`).join('');}el.innerHTML=`<svg viewBox="0 0 ${W} ${H}" class="chart"><line x1="${p}" y1="${zero}" x2="${W-p}" y2="${zero}" class="axis"/>${marks}<path d="${path}" class="diagram-line"/>${labels}<text x="${p}" y="20" class="chart-label">${label} (${unit})</text><text x="${W-p}" y="${H-8}" text-anchor="end" class="chart-label">x (m)</text></svg>`;
}
function showResults(r){
  const d=r.diagrams?.samples||[];const maxAt=(key)=>{if(!d.length)return [0,0];const z=d.reduce((a,b)=>Math.abs(b[key])>Math.abs(a[key])?b:a,d[0]);return [Number(z[key]),Number(z.x)]};
  const [mv,xv]=maxAt('shear_kN'),[mm,xm]=maxAt('moment_kNm'),[md,xd]=maxAt('deflection_mm');$('#maxV').textContent=`${Math.abs(mv).toFixed(3)} kN`;$(`#maxVPos`).textContent=`at ${xv.toFixed(3)} m`;$('#maxM').textContent=`${Math.abs(mm).toFixed(3)} kN·m`;$(`#maxMPos`).textContent=`at ${xm.toFixed(3)} m`;$('#maxD').textContent=`${Math.abs(md).toFixed(3)} mm`;$(`#maxDPos`).textContent=`at ${xd.toFixed(3)} m`;
  $('#reactions').innerHTML=`<table><thead><tr><th>#</th><th>Type</th><th>Position</th><th>Vertical (kN)</th><th>Moment (kN·m)</th></tr></thead><tbody>${r.reactions.map(x=>`<tr><td>${x.index}</td><td>${x.type.replaceAll('_',' ')}</td><td>${Number(x.position).toFixed(3)} m</td><td>${Number(x.vertical_kN).toFixed(3)}</td><td>${Number(x.moment_kNm).toFixed(3)}</td></tr>`).join('')}</tbody></table>`;
  const hc=r.hinge_checks||[];$('#hingeChecks').innerHTML=hc.length?`<table><thead><tr><th>Position</th><th>Left M</th><th>Right M</th></tr></thead><tbody>${hc.map(h=>`<tr><td>${Number(h.position).toFixed(3)} m</td><td>${Number(h.left_moment_kNm).toExponential(3)} kN·m</td><td>${Number(h.right_moment_kNm).toExponential(3)} kN·m</td></tr>`).join('')}</tbody></table>`:'No internal hinges.';
  const features=[...(r.reactions||[]),...(r.hinge_checks||[]),...(state.loads||[])].map(x=>({x:Number(x.position)}));chart($('#sfd'),d,'shear_kN','Shear force','kN',features);chart($('#bmd'),d,'moment_kNm','Bending moment','kN·m',features);chart($('#deflection'),d,'deflection_mm','Deflection','mm',features);chart($('#rotation'),d,'rotation_rad','Rotation / slope','rad',features);
  $('#status').textContent='Solved';window.lastResult=r;
}
async function initPython(){try{pyodide=await loadPyodide({indexURL:'https://cdn.jsdelivr.net/pyodide/v0.26.4/full/'});await pyodide.loadPackage('numpy');const [solverText,diagramText]=await Promise.all([fetch('backend/solver.py').then(r=>{if(!r.ok)throw Error('Could not load Python solver');return r.text()}),fetch('backend/diagrams.py').then(r=>{if(!r.ok)throw Error('Could not load diagram engine');return r.text()})]);pyodide.FS.writeFile('/home/solver.py',solverText);pyodide.FS.writeFile('/home/diagrams.py',diagramText);pyodide.runPython("import sys; sys.path.insert(0, '/home')");pyodide.runPython('import solver, diagrams');solverReady=true;$('#engineStatus').textContent='Python engine ready';$('#status').textContent='Ready';}catch(e){$('#engineStatus').textContent='Python engine failed';$('#error').textContent=e.message||String(e);$('#error').classList.remove('hidden');}}
async function evaluate(){if(!solverReady){$('#error').textContent='Python engine is still loading.';$('#error').classList.remove('hidden');return;}$('#status').textContent='Solving…';$('#error').classList.add('hidden');try{pyodide.globals.set('model_json',JSON.stringify(state));const raw=await pyodide.runPythonAsync(`import json\nmodel=json.loads(model_json)\nr=solver.solve_beam(model)\nr["diagrams"]=diagrams.build_diagrams(model,r)\njson.dumps(r)`);showResults(JSON.parse(raw));}catch(e){$('#status').textContent='Error';$('#error').textContent=e.message||String(e);$('#error').classList.remove('hidden');}}
function saveFile(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='beamlab-model.json';a.click();URL.revokeObjectURL(a.href);}
function loadFile(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.spans)||!Array.isArray(data.supports)||!Array.isArray(data.loads))throw Error('Invalid BeamLab model file');snapshot();state=data;render();}catch(e){$('#error').textContent=e.message;$('#error').classList.remove('hidden');}};r.readAsText(file);}
function newModel(){snapshot();state=clone(initialState);render();$('#error').classList.add('hidden');$('#status').textContent='Ready';}
function loadExample(name){snapshot();if(name==='simple')state={spans:[{length:8,E:200,I:100000000}],supports:[{id:1,type:'pin',position:0,settlement:0},{id:2,type:'roller',position:8,settlement:0}],loads:[{id:1,type:'point',value:10,position:4,angle:0}]};else if(name==='udl')state={spans:[{length:6,E:200,I:100000000}],supports:[{id:1,type:'pin',position:0,settlement:0},{id:2,type:'roller',position:6,settlement:0}],loads:[{id:1,type:'udl',value:10,value2:10,position:0,to:6}]};else state={spans:[{length:4,E:200,I:100000000}],supports:[{id:1,type:'fixed',position:0,settlement:0}],loads:[{id:1,type:'point',value:20,position:4,angle:0}]};render();evaluate();}
function poi(){const x=Number($('#poi').value);const d=window.lastResult?.diagrams?.samples||[];if(!Number.isFinite(x)||!d.length){$('#poiOut').textContent='Evaluate the beam and enter a valid X position.';return;}const s=d.reduce((a,b)=>Math.abs(b.x-x)<Math.abs(a.x-x)?b:a,d[0]);$('#poiOut').innerHTML=`x = <strong>${s.x.toFixed(3)} m</strong><br>V = ${s.shear_kN.toFixed(3)} kN<br>M = ${s.moment_kNm.toFixed(3)} kN·m<br>δ = ${s.deflection_mm.toFixed(3)} mm`}
function printReport(){window.print();}
document.addEventListener('input',e=>{let changed=false;if(e.target.dataset.span!==undefined){snapshot();state.spans[Number(e.target.dataset.span)][e.target.dataset.field]=Number(e.target.value);changed=true;}else if(e.target.dataset.support!==undefined){snapshot();const s=state.supports[Number(e.target.dataset.support)];s[e.target.dataset.field]=e.target.dataset.field==='type'?e.target.value:Number(e.target.value);changed=true;}else if(e.target.dataset.load!==undefined){snapshot();const l=state.loads[Number(e.target.dataset.load)];l[e.target.dataset.field]=Number(e.target.value);changed=true;}if(changed)renderBeam();});
document.addEventListener('change',e=>{if(e.target.dataset.support!==undefined){const s=state.supports[Number(e.target.dataset.support)];s[e.target.dataset.field]=e.target.value;render();}if(e.target.dataset.unit){} });
document.addEventListener('click',e=>{
  if(e.target.id==='solve')evaluate();
  if(e.target.id==='newBtn')newModel();if(e.target.id==='saveBtn')saveFile();if(e.target.id==='loadInput')return;if(e.target.id==='shareBtn'){navigator.clipboard?.writeText(location.href);$('#status').textContent='Link copied';}
  if(e.target.id==='addSpan'){snapshot();state.spans.push({length:4,E:200,I:100000000});render();}
  if(e.target.id==='addSupport'){snapshot();state.supports.push({id:Date.now(),type:'internal_hinge',position:totalLength()/2,settlement:0});render();}
  const add=e.target.closest('[data-add-load]');if(add){snapshot();const type=add.dataset.addLoad;state.loads.push(type==='udl'?{id:Date.now(),type,value:10,value2:10,position:0,to:totalLength()}:type==='moment'?{id:Date.now(),type,value:10,position:totalLength()/2}:{id:Date.now(),type,value:10,position:totalLength()/2,angle:0});render();}
  const rs=e.target.dataset.removeSpan;if(rs!==undefined&&state.spans.length>1){snapshot();state.spans.splice(Number(rs),1);render();}
  const rso=e.target.dataset.removeSupport;if(rso!==undefined){snapshot();state.supports.splice(Number(rso),1);render();}
  const rl=e.target.dataset.removeLoad;if(rl!==undefined){snapshot();state.loads.splice(Number(rl),1);render();}
  if(e.target.id==='undoBtn'&&history.length){future.push(clone(state));restore(history.pop());}
  if(e.target.id==='redoBtn'&&future.length){history.push(clone(state));restore(future.pop());}
  if(e.target.id==='zoomIn'){zoom=Math.min(2,zoom+.1);renderBeam();}if(e.target.id==='zoomOut'){zoom=Math.max(.5,zoom-.1);renderBeam();}if(e.target.id==='resetView'){zoom=1;renderBeam();}
  if(e.target.id==='valueToggle'){showValues=!showValues;e.target.classList.toggle('active',showValues);if(window.lastResult)showResults(window.lastResult);}if(e.target.id==='featureToggle'){showFeatures=e.target.checked;if(window.lastResult)showResults(window.lastResult);}
  if(e.target.id==='poiBtn')poi();if(e.target.id==='reportBtn')printReport();const ex=e.target.closest('[data-example]');if(ex)loadExample(ex.dataset.example);
  if(e.target.id==='themeBtn'){document.body.classList.toggle('light');localStorage.setItem('beamlab-theme',document.body.classList.contains('light')?'light':'dark');}
});
$('#loadInput').addEventListener('change',e=>{if(e.target.files[0])loadFile(e.target.files[0]);});
if(localStorage.getItem('beamlab-theme')==='light')document.body.classList.add('light');
render();initPython();
